name: Deploy Python Azure Function

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: fn-iot-ehub
  AZURE_RESOURCE_GROUP: iot-gen-ehub
  PYTHON_VERSION: '3.11'
  FUNCTION_DIR: function_app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies (optional if not pre-packaged)
      working-directory: ${{ env.FUNCTION_DIR }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip Function App for deployment
      run: |
        cd $FUNCTION_DIR
        zip -r ../functionapp.zip .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Function App
      run: |
        az functionapp deployment source config-zip \
          --resource-group $AZURE_RESOURCE_GROUP \
          --name $AZURE_FUNCTIONAPP_NAME \
          --src functionapp.zip
