name: Deploy Python Azure Function

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: fn-iot-ehub
  AZURE_RESOURCE_GROUP: iot-gen-ehub
  PYTHON_VERSION: '3.10'
  FUNCTION_DIR: function_app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      working-directory: ${{ env.FUNCTION_DIR }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # New step: Install Azure Functions Core Tools
    - name: Install Azure Functions Core Tools
      run: |
        npm install -g azure-functions-core-tools@4 --unsafe-perm true

    # --- NEW DEBUGGING STEP ---
    - name: 💡 Install tree for debugging
      run: sudo apt-get install tree

    - name: 💡 Show file structure before zipping
      working-directory: ${{ env.FUNCTION_DIR }}
      run: tree .

    - name: 💡 Check dependencies for debugging
      run: pip freeze
       
    # --- END NEW DEBUGGING STEP ---
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # New step: Deploy with Core Tools, replacing the old 'Zip' and 'Deploy' steps
    - name: Deploy to Azure Function App with Core Tools
      run: |
        func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --python \
          --build-native-deps \
          --force
      working-directory: ${{ env.FUNCTION_DIR }}
          
    - name: Restart Function App (force sync)
      run: |
        az functionapp restart --name $AZURE_FUNCTIONAPP_NAME --resource-group $AZURE_RESOURCE_GROUP
    
    - name: List deployed functions
      run: |
        sleep 30 # Give time for the function to be discovered after restart
        az functionapp function list --name $AZURE_FUNCTIONAPP_NAME --resource-group $AZURE_RESOURCE_GROUP --output table
















